### ISSUE TITLE
pls. open "issues" sections

### ISSUE THREAD

**Issue by DI555** [rushiranpise/userscripts#1]
pardon me for posting it here, but no other place for this now((

@rushiranpise ,
please, could you open "issues" sections in "AyuGram4A" and "AyuGramDesktop" repos, there are some really good wishes about to be there
many thanks in advance!

**Comment by rushiranpise** [comment]
Hi!.please follow the original repos

https://github.com/AyuGram/AyuGramDesktop

https://github.com/AyuGram/AyuGram4A

**Comment by DI555** [comment]
there are, unfortunately, no any issues.. all is discussing in a chat.., but my issues take only building things, no any fr’s at all..

and for sure, all issues in your repos of ayugram should be only about buildings and of the buildings and builds !!!

**Comment by DI555** [comment]
for example, i just wanted to ask you to cut off any gcm/fcm/trackers/telemetry blobs integrations in the builds, because of sensitive data leaks danger in case of it ..
